import 'package:capture/features/capture/domain/entities/approval_problem.dart';
import 'package:capture/features/capture/domain/entities/due_date.dart';
import 'package:capture/features/capture/domain/entities/edited_field.dart';
import 'package:capture/features/capture/domain/entities/item_kind.dart';
import 'package:capture/features/capture/domain/entities/review_flag.dart';
import 'package:capture/features/capture/domain/entities/source_span.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'proposal_item.freezed.dart';

/// One proposed note or task. Built by code from Jev decisions and source
/// text; the user's edits always take precedence over suggestions.
@freezed
sealed class ProposalItem with _$ProposalItem {
  const ProposalItem._();

  const factory ProposalItem({
    /// Stable item id generated by code before any request.
    required String id,

    /// Supporting source passages (offsets + exact excerpts), in order.
    required List<SourceSpan> sources,
    required ItemKind kind,

    /// Notion page id of the group; null only while the user must choose.
    required String? groupId,
    required String title,

    /// Editable body; starts as a copy of the source text.
    required String body,
    DueDate? due,

    /// Local wall-clock reminder time in the capture time zone.
    DueDate? reminder,
    @Default({}) Set<ReviewFlag> flags,
    @Default({}) Set<EditedField> edited,

    /// False when the user removed the item (or recall-only questions).
    @Default(true) bool included,
  }) = _ProposalItem;

  String get sourceText => sources.map((s) => s.excerpt).join(' ');

  bool get isTask => kind == .task;

  ProposalItem withTitle(String value) => copyWith(title: value, edited: {...edited, .title});

  ProposalItem withBody(String value) => copyWith(body: value, edited: {...edited, .body});

  ProposalItem withGroup(String value) => copyWith(
    groupId: value,
    edited: {...edited, .group},
    flags: flags.difference({ReviewFlag.checkGroup, ReviewFlag.newPiece}),
  );

  ProposalItem withKind(ItemKind value) => copyWith(
    kind: value,
    edited: {...edited, .kind},
    due: value == .note ? null : due,
    reminder: value == .note ? null : reminder,
    flags: flags.difference({
      ReviewFlag.checkTask,
      ReviewFlag.newPiece,
      if (value == .note) ...ReviewFlag.dateFlags,
    }),
  );

  /// Sets or clears the due date. [checks] are the resolver's flags for the
  /// new value (e.g. time passed / clock change).
  ProposalItem withDue(DueDate? value, {Set<ReviewFlag> checks = const {}}) => copyWith(
    due: value,
    edited: {...edited, .due},
    flags: flags.difference(ReviewFlag.dueFlags).union(checks),
  );

  /// Sets or removes the reminder; a reminder implies a task.
  ProposalItem withReminder(DueDate? value, {Set<ReviewFlag> checks = const {}}) => copyWith(
    kind: value == null ? kind : .task,
    reminder: value,
    due: value == null ? due : due ?? value,
    edited: {...edited, .reminder},
    flags: flags.difference(ReviewFlag.dateFlags).union(checks),
  );

  ProposalItem withIncluded({required bool value}) {
    final ProposalItem next = copyWith(included: value, edited: {...edited, .included});
    return next;
  }

  /// Problems that block approval while this item is included.
  Set<ApprovalProblem> get approvalProblems => included
      ? {
          if (groupId == null) ApprovalProblem.chooseGroup,
          if (title.trim().isEmpty) ApprovalProblem.addTitle,
          if (flags.contains(ReviewFlag.chooseAmPm)) ApprovalProblem.chooseAmPm,
          if (flags.contains(ReviewFlag.clockChange) && reminder != null)
            ApprovalProblem.checkClockChange,
        }
      : const {};
}
